# Probably will be usefully for Models in the future

controlnet_paths:
  normal_bae: "lllyasviel/control_v11p_sd15_normalbae"
  canny: "lllyasviel/control_v11p_sd15_canny"
  softedge_hed: "lllyasviel/control_v11p_sd15_softedge"
  depth_midas: "lllyasviel/control_v11f1p_sd15_depth"

style-tokens:
  tst2:
    controlnet:
      name: [ "depth_midas", "canny" ]
      weights: [ 0.2, 0.4 ]
  tst5:
    controlnet:
      name: [ "canny", "normal_bae" ]
      weights: [ 0.9, 0.2 ]
