# Probably will be usefully for Models in the future

controlnet_paths:
  normal_bae: "lllyasviel/control_v11p_sd15_normalbae"
  canny: "lllyasviel/control_v11p_sd15_canny"
  softedge_hed: "lllyasviel/control_v11p_sd15_softedge"
  depth_midas: "lllyasviel/control_v11f1p_sd15_depth"

style-tokens:
  tst2:
    controlnet:
      name: [ "normal_bae", "canny" ]
      weights: [ 0.1, 0.40 ]
  tst5:
    controlnet:
      name: [ "canny", "depth_midas" ]
      weights: [ 0.8, 0.3 ]
  tst7:
    controlnet:
      name: [ "canny", "normal_bae" ]
      weights: [ 1, 0.5 ]
