# Probably will be useful for Models in the future

controlnet_paths:
  normal_bae: "lllyasviel/control_v11p_sd15_normalbae"
  canny: "lllyasviel/control_v11p_sd15_canny"
  softedge_hed: "lllyasviel/control_v11p_sd15_softedge"
  depth_midas: "lllyasviel/control_v11f1p_sd15_depth"
  lineart_realistic: "lllyasviel/control_v11p_sd15_lineart"


style-tokens:
  tst2:
    controlnet:
      name: [ "normal_bae", "canny" ]
      weights: [ 0.1, 0.5 ]
  tst5:
    controlnet:
      name: [ "canny", "depth_midas" ]
      weights: [ 0.8, 0.3 ]
  tst4:
    controlnet:
      name: [ "canny", "depth_midas"]
      weights: [ 0.1, 0.6 ]
  tst7:
    controlnet:
      name: [ "depth_midas", "canny" ]
      weights: [ 0.5 , 1 ]

